### ISSUE TITLE
Reading .ndax files

### ISSUE THREAD

**Issue by Mitchal-Dichter** [FTHuld/neware_reader#6]
Are there any plans to include reading of the newest .ndax Neware files in this project?

Similar to the creation of this project from nda-extractor by thebestpatrick, the newest Neware software changed the file format. I was able to contact Neware, but the most information they would provide about the new .ndax format was that it's similar to the .nda format and would not release more details about their intellectual property. I looked into the file with a binary viewer, but the NEWARE characters at the beginning of the .nda format was missing from the .ndax file.

I did find a reference in some Neware brochures for a "Standard API included, especially for 3rd party equipment integration and large-scale production" but that's all I found.
![Capture](https://user-images.githubusercontent.com/82119172/113926456-08513280-97a1-11eb-950a-7f1c8c918882.PNG)
https://www.newareusa.com/wp-content/uploads/2020/05/Neware-whole-products-catalog-2019.pdf
I'm hoping maybe possibly the API exists and you are using it in lieu of making your own .ndax parser. 

If not, how did you possibly accomplish this? I'd be happy to share my findings in exchange for a little guidance. I tried some simple things like finding human readable strings in the .ndax file and comparing two .ndax files, but that yielded little progress. Then I tried changing bytes in the .ndax file, exporting csv files for the original and changed .ndax, then looking for what cell value changed between the two, but BTSDAEx.exe said the .ndax I changed was malformed.

I'm stuck. Any ideas?

**Comment by FTHuld** [comment]
Hi @Mitchal-Dichter .

I'm afraid that at the moment I have no plan to add .ndax files to the package. However, that's only because I haven't upgraded to the new software version, and I don't have any .ndax files to test with.

Do you think you could send me a small file to play with, along with the version of the software you used?

The original package was made by comparing/finding values in the byte stream that match those shown by the neware software, and then figuring out how wide each line of data was. If the line width and data position is the same or similar in the newest version, it shouldn't be too difficult to include the newest version in the package.

I wasn't aware that there was an API, but in my defence it doesn't seem to be mentioned anywhere except the image you linked.

**Comment by Mitchal-Dichter** [comment]
Hi @FTHuld,
Here is a link to an .ndax file, converted CSV, and the new Neware software.
https://drive.google.com/file/d/1vSig1rbNoqwhjqmrvWOrB4w0kO2hEMx2/view?usp=sharing
If you can't open the zip, Windows did complain about a capital greek Omega symbol in a file name somewhere. Let me know and I'll try to fix it.

The .ndax reader is BTSDAEx.exe and it must remain in its relative location in the folder to work, unlike the previous .nda reader.

I looked at the byte stream, but didn't get very far. There was some obvious text with names of .xml files, and I think some date times, but I didn't get very far.

**Comment by FTHuld** [comment]
Hi @Mitchal-Dichter 

Thank you for the files.

It looks like the .ndax file is a compressed file. I noticed that when you open it in BTSDAEx, it creates a `/tmp` folder in `/NdaData` (and if `/NdaData` is missing, it creates that too). That `/tmp` folder contains a folder with a unique string, which contains the data itself, called `data.ndc` as well as .xml files with info about the procedure.

The good news is that we can use the `data.ndc` file to extract the data. The bad news is that the BTSDAEx software deletes the folder when it is closed, so the .ndax file needs to be open in BTSDAEx in order for us to be able to access the .ndc file. Luckily for us, BTSDAEx also creates a log file with the path to the .ndc file, so we can use python to open the .ndax in BTSDAEx, find the correct path to the .ndc file, extract our data, then close the program.

Looking at the data.ndc file (I use HxD) it seems to be divided into rows of 512 bytes, with each row containing 5 datapoints worth of data. Each of these data fragments consists of 94 bytes, with a few extra bytes at the end of the line (94*5 + 42 = 512).

It'll take me some time to find which positions in the byte stream correspond to which piece of information. If you manage to find which fragments correspond to which data please let me know so we don't duplicate our efforts.

If we're lucky, these .ndc files are the same as those created by other machines, so we can add a ndc_to_csv() to the package that can circumvent using .nda/.ndax files completely.

@KarlNorway Has your team switched to BTSDA version 8 yet? I'm thinking that being able to convert directly from .ndc to .csv (or read .ndc directly into python) might be quite useful for your group too?

**Comment by KarlNorway** [comment]
@FTHuld  We did do the update but have stuck with NDA (selectable in the settings) I have not had the time to investigate yet. 

I also know that Neware uses a SQL database to store all data befor it is presented in BTSDA.

I have been able to see the database in different tools but know any user or password so no luck there. 

I might be able to look in to decoding in mid May. 

It would be really nice to have this added to the repo

**Comment by Mitchal-Dichter** [comment]
Hi @FTHuld,
You're welcome! Those files are currently hard to come by too. As far as I can tell, all the Neware links to download them are broken, but the web pages with the links are still there.

Actually, we're going to go with setting BTS to output an excel file for each test rather than trying to read the .nda, .ndax, or .ndc files directly. I would prefer to read the Neware files directly with python, but Neware has not made automation easy. Even though I will end up with multiple header formats for my python code to parse, I know I can read the excel files successfully.

Good luck!

**Comment by KarlNorway** [comment]
@Mitchal-Dichter @FTHuld  I can make a couple of files tomorrow if any of you want. 

@Mitchal-Dichter I have a script running that converts NDA files (in batch sort of) that I can share. The output is HDF5 or what ever you want. 

I found the Excel files to be quite messy with all the different sheets, but that's just my opinion. Please let me know if you want the script, this repo neede

**Comment by FTHuld** [comment]
Yes please @KarlNorway. 

I think it might be time to restructure the way this repository works, especially since it looks like users want to use it for automation.

I'm thinking branching from the dictionary to easily include more data formats (including hdf5), and iterating from the end of the files so we can append new data to existing files (instead of recreating files from scratch every time). That should speed things up considerably.

The existing functionality shouldn't change, just the way in which we get to the result.

@Mitchal-Dichter for now I suggest sticking with nda files like @KarlNorway is doing, or excel files if that's what you prefer.

**Comment by KarlNorway** [comment]
@FTHuld @Mitchal-Dichter I hav noe successfuly access the database from both remote computer and local computer. 
Finding the header info was a bit of hassle but the data transfer is faster than going throug NDA files.

PM for more info.

Will branch out for this purpose

**Comment by KarlNorway** [comment]
Sorry for late reply. I just figured out that the NDC file have a set data length but no header info. You need to know what you ser suppsoed to be cycling on the channel.

Each 5th line is longer and have some extra data, wich makes the data conversion harder.

For the database after looking at two tables we get all the info we need and conversion to dataframe or other format is faster.

**Comment by FTHuld** [comment]
I think the ndc has 512-byte lines each containing 5 lines of data. The 42 bytes at the end of the 5th line are just left over because 512/5 isn't an even number. I'm not sure what the final 4-byte column at the end is for as I'm not seeing a pattern in it. Some kind of end-of-line trigger perhaps?

Converting directly from the SQL DB is the most elegant solution, but that wouldn't work if you don't have acces to the DB, right? What software do you use to see the data in the DB?

**Comment by KarlNorway** [comment]
I'm using Python with sql.connect package.

Look for email ;)

**Comment by Mitchal-Dichter** [comment]
@KarlNorway You said "We did do the update but have stuck with NDA (selectable in the settings) I have not had the time to investigate yet." Can you share a screenshot of the settings where NDA can be chosen over NDAX in the BTS8.0 GUI please? I can't seem to find it.

As for my plan of just reading the xlsx files, we have tests that are running for months and the entire computer is becoming unresponsive when Neware tries to update these >100MB xlsx files. Reading NDA files is becoming necessary. Also, our talks with Neware tech support are saying that the NDA files won't be an option in the near future. Sounds like an upcoming model of Neware equipment will have to use NDAX files.

**Comment by KarlNorway** [comment]
In the settings:
![image](https://user-images.githubusercontent.com/20084966/119091221-066bc780-ba0d-11eb-8402-779b58407072.png)

But if you have the "cycling computer" connected to a network with the analysis machine:

The neware uses a SQL database to store all cycling data in. 
@Mitchal-Dichter  email me: karlkristian.markman@gmail.com and I will explain how to access the DB
